# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'babycare' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for babycare
  pod 'Firebase/Core'
  pod 'Firebase/AdMob'

  target 'babycareTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'babycare-tvOS' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for babycare-tvOS

  target 'babycare-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
